### ISSUE TITLE
Build errors: undefined things

### ISSUE THREAD

**Issue by clehner** [6c37/gone#1]
I get the following build errors. I'm not too familiar with Go so I'm not sure how to fix these.
```
# github.com/6c37/gone
/home/cel/go/src/github.com/6c37/gone/main.go:32: undefined: ParametersFiles
/home/cel/go/src/github.com/6c37/gone/main.go:35: undefined: Response
/home/cel/go/src/github.com/6c37/gone/main.go:56: undefined: ParametersFiles
```
go version go1.4.2 linux/amd64
Debian testing

**Comment by kori** [comment]
`gone` is undergoing serious restructuring right now, I apologize for the build errors, they should be sorted in a couple days.
You can use [tek](https://github.com/6c37/tek) for now if you'd like such a program.

**Comment by clehner** [comment]
Ok, thanks.

**Comment by kori** [comment]
Actually, if you fetch the repo as it is right now, it should work.

**Comment by clehner** [comment]
Awesome!

**Comment by kori** [comment]
Usage is `gone -w teknik -f <file>` for that version of the program, by the way.
